animalIndex:
    path: /animal
    controller: App\Controller\AnimalController::index

animalSave:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    
animalDetail:
    path: /animal/detail/{id}
    controller: App\Controller\AnimalController::animal
    
animalUpdate:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::upDate

animalDelete:
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::delete

animalCreate:
    path: /animal/create/
    controller: App\Controller\AnimalController::create

validarEmail:
    path: /animal/validar-email/{email}
    controller: App\Controller\AnimalController::validarEmail
    